src/Entity/Parecer.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ParecerRepository")
 */
class Parecer implements EntityInterface, LimiterEscolaInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $data_hora;

    /**
     * @ORM\Column(type="blob")
     * @Assert\NotBlank()
     */
    private $descricao;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Aluno", inversedBy="pareceres")
     * @ORM\JoinColumn(nullable=false)
     */
    private $aluno;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Usuario", inversedBy="pareceres")
     * @ORM\JoinColumn(nullable=false)
     */
    private $usuario;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $titulo;

    /**
     * Parecer constructor.
     */
    public function __construct()
    {
        $this->data_hora = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDataHora(): ?\DateTimeInterface
    {
        return $this->data_hora;
    }

    public function setDataHora(\DateTimeInterface $data_hora): self
    {
        $this->data_hora = $data_hora;

        return $this;
    }

    public function getDescricao()
    {
        return !empty($this->descricao) ? stream_get_contents($this->descricao) : $this->descricao;
    }

    public function setDescricao($descricao): self
    {
        $this->descricao = $descricao;

        return $this;
    }

    public function getAluno(): ?Aluno
    {
        return $this->aluno;
    }

    public function setAluno(?Aluno $aluno): self
    {
        $this->aluno = $aluno;

        return $this;
    }

    public function getUsuario(): ?Usuario
    {
        return $this->usuario;
    }

    public function setUsuario(?Usuario $usuario): self
    {
        $this->usuario = $usuario;

        return $this;
    }

    public function getTitulo(): ?string
    {
        return $this->titulo;
    }

    public function setTitulo(?string $titulo): self
    {
        $this->titulo = $titulo;

        return $this;
    }

    public function getEscola(): ?Escola
    {
        return $this->getAluno()->getEscola();
    }
}

src/Controller/TimelineController.php
<?php
/**
 * Created by PhpStorm.
 * User: tiago
 * Date: 14/10/18
 * Time: 13:31.
 */

namespace App\Controller;

use App\Repository\AlunoRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class TimelineController.
 *
 * @Route("/timeline")
 */
class TimelineController extends AbstractController
{
    private $aluno;

    public function __construct(SessionInterface $session, AlunoRepository $alunoRepository)
    {
        if (null !== $session->get('aluno_id')) {
            $this->aluno = $alunoRepository->find($session->get('aluno_id'));
        }
    }

    /**
     * @Route("/{entityOpenner}/{orientation}", name="timeline_index", defaults={"entityOpenner"="","orientation"="horizontal"})
     * @IsGranted("aluno_show")
     */
    public function index(string $entityOpenner, string $orientation): Response
    {
        return $this->render('timeline/index.html.twig', [
            'entityOpenner' => $entityOpenner,
            'register' => $this->aluno,
            'timelineElements' => $this->aluno->getTimelineElements(),
            'orientation' => $orientation,
        ]);
    }
}

templates/timeline/_card.html.twig
{% if entityOpenner == 'acompanhamento' %}
    {% set actionList = {
        'copy': true,
        'copy_link': false,
        'show': true,
        'edit': true,
        'delete': true,
        'pdf': true,
    } %}
{% else %}
    {% set actionList = {
        'copy': true,
        'copy_link': true,
        'show': true,
        'edit': true,
        'delete': true,
        'pdf': true,
    } %}
{% endif %}


{% if timelineElement is Comentario %}
    {% set entityType = 'comentario' %}
    {% set displayName = 'Foto/Vídeo' %}
    {% set icon = 'fa-camera-retro' %}
    {% set actionList = actionList|merge({
        'pdf':false,
    }) %}
{% endif %}
{% if timelineElement is Acompanhamento %}
    {% set entityType = 'acompanhamento' %}
    {% set displayName = 'Acompanhamento' %}
    {% set icon = 'fa-file' %}
{#    {% set actionList = actionList|merge({#}
{#        'copy_link':false,#}
{#    }) %}#}
{% endif %}
{% if timelineElement is Parecer %}
    {% set entityType = 'parecer' %}
    {% set displayName = 'Parecer' %}
    {% set icon = 'fa-file-powerpoint' %}
{% endif %}
{% if timelineElement is Formulario %}
    {% set entityType = 'formulario_dinamico' %}
    {% set displayName = 'Formulário' %}
    {% set icon = 'fa-file-signature' %}
    {% set actionList = actionList|merge({
        'copy':false,
        'copy_link':false,
        'show': false,
    }) %}
{% endif %}


<div class="card mb-3 entity-card" data-entity="{{ entityType }}">
    <div class="card-header">
        <i class="fas {{ icon }}"></i> {{ displayName }}
        {% include 'timeline/_card_vertical_actions.html.twig' with {register: timelineElement, entityType: entityType, orientation: orientation, actionList: actionList} only  %}
    </div>
    {% include 'timeline/_card_horizontal_actions.html.twig' with {register: timelineElement, entityType: entityType, orientation: orientation, actionList: actionList} only  %}
    {% include 'timeline/_card_'~entityType~'.html.twig' with {register: timelineElement, entityType: entityType, orientation: orientation} only  %}
</div>

templates/timeline/_card_acompanhamento.html.twig
<div class="card-body">
    <h6 class="card-title">De: {{ register.usuario.nome }}</h6>
    <p class="card-text"><small class="text-muted">{{ register.dataHora ? register.dataHora|date('d/m/Y H:i:s') : '' }}</small></p>
    <div class="card-text" id="register_{{ entityType }}_{{ register.id }}">{{ register.descricao|raw }}</div>
</div>

templates/timeline/_card_comentario.html.twig
<div class="card-body" >
    <h6 class="card-title">De: {{ register.usuario.nome }}</h6>
    <p class="card-text"><small class="text-muted">{{ register.dataHora ? register.dataHora|date('d/m/Y H:i:s') : '' }}</small></p>
    <div class="card-text" id="register_{{ entityType }}_{{ register.id }}">
        {{ register.descricao }}

        {% if register.file is defined %}
            <div class="col-lg-7 mx-auto">
                {% if(register.file.extension =="mp4") %}
                    <video width="100%" controls>
                        <source src="{{ asset('uploads/' ~ register.file.filename  ) }}" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                {% else %}
                    <img  class="img-comenatios" src="{{ asset('uploads/' ~ register.file.filename  ) }}" alt="Arquivo do comentário">
                {% endif %}
            </div>
        {% endif %}
    </div>
</div>

templates/timeline/_card_formulario_dinamico.html.twig
<div class="card-body">
    <h6 class="card-title">De: {{ register.usuario.nome }}</h6>
    <p class="card-text"><small class="text-muted">{{ register.dataHora ? register.dataHora|date('d/m/Y H:i:s') : '' }}</small></p>
    <div class="card-text" id="register_{{ entityType }}_{{ register.id }}">{{ register.formulario.nome}}</div>
</div>

templates/timeline/_card_horizontal_actions.html.twig
{% if orientation == 'horizontal' %}
    <div class="card-header" >

        {% if(actionList.copy is defined and actionList.copy == true) %}
            <a class="card-horizontal-action" href="#"
               onclick="copyValue('register_{{ entityType }}_{{ register.id }}')">
                <i class="fas fa-copy" title="Importar conteúdo"></i>
            </a>
        {% endif %}

        {% if(actionList.copy_link is defined and actionList.copy_link  == true) %}

            <a class="card-horizontal-action" href="#"
               onclick="copyValueWithLink('register_{{ entityType }}_{{ register.id }}','{{ path(entityType~'_show', {id: register.id}) }}')">
                <i class="fas fa-link" title="Importar conteúdo com link"></i>
            </a>
        {% endif %}

        {% if(actionList.show is defined and actionList.show  == true) %}
            {% if register is Formulario %}
                <a class="card-horizontal-action"
                   href="{{ path(entityType~'_report_pdf', {form_id: register.formulario.id, id: register.id}) }}"
                   target="_blank">
                    <i class="fas fa-eye" title="Visualizar registro"></i>
                </a>
            {% else %}
                <a class="card-horizontal-action" href="{{ path(entityType~'_show', {id: register.id}) }}"
                   target="_blank">
                    <i class="fas fa-eye" title="Visualizar registro"></i>
                </a>
            {% endif %}
        {% endif %}

    </div>
{% endif %}

templates/timeline/_card_parecer.html.twig
<div class="card-body">
    <h6 class="card-title">De: {{ register.usuario.nome }}</h6>
    <p class="card-text"><small class="text-muted">{{ register.dataHora ? register.dataHora|date('d/m/Y H:i:s') : '' }}</small></p>
    <div class="card-text" id="register_{{ entityType }}_{{ register.id }}">{{ register.descricao|raw }}</div>
</div>

templates/timeline/_card_vertical_actions.html.twig
{% if orientation == 'vertical' %}
    <div style="float: right;">

        <div class="dropdown dropleft monitor-hide">
            <img class="dropdown-toggle"
                 src="{{ asset('assets/img/menu.png') }}"
                 id="dropdownMenuButton" data-toggle="dropdown"
                 style="cursor: pointer"
                 aria-haspopup="true"
                 aria-expanded="false">

            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" >

                {% if(actionList.show is defined and actionList.show  == true) %}
                    <a class="card-horizontal-action" href="{{ path(entityType~'_show', {id: register.id}) }}"
                       target="_blank">
                        <i class="fas fa-eye" title="Visualizar registro"></i> Visualizar
                    </a>
                {% endif %}

                {% if(actionList.pdf is defined and actionList.pdf  == true) %}
                    {% if register is Formulario %}
                        <a class="card-horizontal-action"
                           href="{{ path(entityType~'_report_pdf', {form_id: register.formulario.id, id: register.id}) }}"
                           target="_blank">
                            <i class="fas fa-file-pdf" title="Gerar PDF"></i> PDF
                        </a>
                    {% else %}
                        <a class="card-horizontal-action" href="{{ path(entityType~'_report_pdf', {id: register.id}) }}"
                           target="_blank">
                            <i class="fas fa-file-pdf" title="Gerar PDF"></i> PDF
                        </a>
                    {% endif %}
                {% endif %}

                {% if(actionList.edit is defined and actionList.edit  == true and register.usuario == app.user) %}
                    {% if register is Formulario %}
                        <a class="card-horizontal-action"
                           href="{{ path(entityType~'_edit', {form_id: register.formulario.id, id: register.id}) }}">
                            <i class="fa fa-edit"></i> Editar
                        </a>
                    {% else %}
                        <a class="card-horizontal-action" href="{{ path(entityType~'_edit', {id: register.id}) }}">
                            <i class="fa fa-edit"></i> Editar
                        </a>
                    {% endif %}
                {% endif %}

                {% if(actionList.delete is defined and actionList.delete == true and register.usuario == app.user) %}
                    <form method="post" id="form_delete_mobile_{{ entityType }}_{{ register.id }}" class="form-delete"
                          action="{{ path(entityType~'_delete', {'id': register.id}) }}">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ register.id) }}">
                        <a class="card-horizontal-action" style="color: red; cursor: pointer"
                           onClick="if(confirm('Tem certeza que deseja excluir?')){
                                   form_delete_mobile_{{ entityType }}_{{ register.id }}.submit()
                                   };">
                            <i class="fa fa-trash"></i> Excluir
                        </a>
                    </form>
                {% endif %}

            </div>
        </div>

        <div class="mobile-hide" >
            {% if(actionList.delete is defined and actionList.delete == true and register.usuario == app.user) %}
                <form method="post" id="form_delete_normal_{{ entityType }}_{{ register.id }}" class="form-delete"
                      action="{{ path(entityType~'_delete', {'id': register.id}) }}">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ register.id) }}">
                    <a class="card-horizontal-action" style="color: red; cursor: pointer"
                       onClick="if(confirm('Tem certeza que deseja excluir?')){
                               form_delete_normal_{{ entityType }}_{{ register.id }}.submit()
                               };">
                        <i class="fa fa-trash"></i> Excluir
                    </a>
                </form>
            {% endif %}

            {% if(actionList.edit is defined and actionList.edit  == true and register.usuario == app.user) %}
                {% if register is Formulario %}
                    <a class="card-horizontal-action"
                       href="{{ path(entityType~'_edit', {form_id: register.formulario.id, id: register.id}) }}">
                        <i class="fa fa-edit"></i> Editar
                    </a>
                {% else %}
                    <a class="card-horizontal-action" href="{{ path(entityType~'_edit', {id: register.id}) }}">
                        <i class="fa fa-edit"></i> Editar
                    </a>
                {% endif %}
            {% endif %}

            {% if(actionList.pdf is defined and actionList.pdf  == true) %}
                {% if register is Formulario %}
                    <a class="card-horizontal-action"
                       href="{{ path(entityType~'_report_pdf', {form_id: register.formulario.id, id: register.id}) }}"
                       target="_blank">
                        <i class="fas fa-file-pdf" title="Gerar PDF"></i> PDF
                    </a>
                {% else %}
                    <a class="card-horizontal-action" href="{{ path(entityType~'_report_pdf', {id: register.id}) }}"
                       target="_blank">
                        <i class="fas fa-file-pdf" title="Gerar PDF"></i> PDF
                    </a>
                {% endif %}
            {% endif %}

            {% if(actionList.show is defined and actionList.show  == true) %}
                <a class="card-horizontal-action" href="{{ path(entityType~'_show', {id: register.id}) }}"
                   target="_blank">
                    <i class="fas fa-eye" title="Visualizar registro"></i> Visualizar
                </a>
            {% endif %}
        </div>

    </div>
{% endif %}

templates/timeline/index.html.twig
<div class="card text-center" style="margin-top: 5px">
    <div class="card-header">
        <ul class="nav nav-pills card-header-pills">
            <li class="nav-item">
                <a id='all' onclick="filterEntity(this.id)" class="nav-link entity-filter" href="#">Tudo</a>
            </li>
            <li class="nav-item">
                <a id='comentario' onclick="filterEntity(this.id)" class="nav-link entity-filter" href="#">Fotos/Vídeos</a>
            </li>
            <li class="nav-item">
                <a id='acompanhamento' onclick="filterEntity(this.id)" class="nav-link entity-filter" href="#">Acompanhamentos</a>
            </li>
            <li class="nav-item">
                <a id='parecer' onclick="filterEntity(this.id)" class="nav-link entity-filter" href="#">Pareceres</a>
            </li>
            <li class="nav-item">
                <a id='formulario_dinamico' onclick="filterEntity(this.id)" class="nav-link entity-filter" href="#">Formulários</a>
            </li>
        </ul>
    </div>
    <div class="card-body" style="text-align: left;">
        {% if orientation == 'horizontal' %}
            <div class="card-group card-group-scroll">
        {% endif %}
            {% for timelineElement in timelineElements %}
                {% include 'timeline/_card.html.twig' with {timelineElement: timelineElement, orientation: orientation, entityOpenner: entityOpenner} only %}
            {% endfor %}
        {% if orientation == 'vertical' %}
        </div>
        {% endif %}
    </div>
</div>

{% block javascripts %}
    <script src="{{ asset('assets/js/jquery.js') }}"></script>

    <script type="text/javascript">
        $(function() {
            filterEntity = function (entityType) {
                $('.entity-filter').removeClass('active');
                $('a#'+entityType).addClass('active');

                $('.entity-card').css('display','none');
                if(entityType == 'all'){
                    $('.entity-card').css('display','');
                }else{
                    $("div[data-entity='"+entityType+"'").css('display','');
                }
            }
        });

        copyValue = function (element){
            data = $("#"+element).html();
            editor = CKEDITOR.instances.{{ entityOpenner }}_descricao;
            editor.setData(editor.getData()+data);
        }

        copyValueWithLink = function (element, link){
            data = $("#"+element).html();

            //TODO: Estudar forma de inibir mensagem de erro do CKEditor
            data = data.replace("Your browser does not support the video tag.","");

            data = "<a target='_blank' href='"+link+"'>"+data+"</a>";
            editor = CKEDITOR.instances.{{ entityOpenner }}_descricao;
            editor.setData(editor.getData()+data);
        }
    </script>
{% endblock %}