src/Entity/Acompanhamento.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AcompanhamentoRepository")
 */
class Acompanhamento implements EntityInterface, LimiterEscolaInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $data_hora;

    /**
     * @ORM\Column(type="blob")
     * @Assert\NotBlank()
     */
    private $descricao;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Aluno", inversedBy="acompanhamentos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $aluno;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Usuario", inversedBy="acompanhamentos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $usuario;

    public function __construct()
    {
        $this->data_hora = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDataHora(): ?\DateTimeInterface
    {
        return $this->data_hora;
    }

    public function setDataHora(\DateTimeInterface $data_hora): self
    {
        $this->data_hora = $data_hora;

        return $this;
    }

    public function getDescricao()
    {
        return !empty($this->descricao) ? stream_get_contents($this->descricao) : $this->descricao;
    }

    public function setDescricao($descricao): self
    {
        $this->descricao = $descricao;

        return $this;
    }

    public function getAluno(): ?Aluno
    {
        return $this->aluno;
    }

    public function setAluno(?Aluno $aluno): self
    {
        $this->aluno = $aluno;

        return $this;
    }

    public function getUsuario(): ?Usuario
    {
        return $this->usuario;
    }

    public function setUsuario(?Usuario $usuario): self
    {
        $this->usuario = $usuario;

        return $this;
    }

    public function getEscola(): ?Escola
    {
        return $this->getAluno()->getEscola();
    }
}

src/Form/AcompanhamentoType.php
<?php

namespace App\Form;

use App\Entity\Acompanhamento;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AcompanhamentoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('descricao', TextareaType::class, [
                'attr' => ['class' => 'ckeditor'],
                'label' => 'Descrição',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Acompanhamento::class,
        ]);
    }
}

src/Controller/AcompanhamentoController.php
<?php

namespace App\Controller;

use App\Entity\Acompanhamento;
use App\Entity\EntityInterface;
use App\Form\AcompanhamentoType;
use App\Service\TemplateManager;
use App\Repository\AcompanhamentoRepository;
use App\Repository\AlunoRepository;
use App\Service\PdfGenerator;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @Route("/acompanhamento")
 */
class AcompanhamentoController extends AbstractAppController
{
    protected $aluno;

    public function __construct(AcompanhamentoRepository $entityRepository, SessionInterface $session, AlunoRepository $alunoRepository)
    {
        $this->entity = new Acompanhamento();
        $this->entityRepository = $entityRepository;
        $this->entityName = 'acompanhamento';
        $this->formType = AcompanhamentoType::class;

        if (null !== $session->get('aluno_id')) {
            $this->aluno = $alunoRepository->find($session->get('aluno_id'));
        }
    }

    /**
     * @Route("/{page}/page", name="acompanhamento_index", methods="GET|POST", defaults={"page" = 1})
     * @IsGranted("acompanhamento_list")
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        return parent::index($paginator, $request);
    }

    /**
     * @Route("/new", name="acompanhamento_new", methods="GET|POST")
     * @IsGranted("acompanhamento_new")
     */
    public function new(Request $request, UserInterface $user): Response
    {
        $form = $this->createForm($this->formType, $this->entity);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // TODO: Isolar em metodo dependente de UserInterface?
            $this->entity->setUsuario($user);

            $this->entity->setAluno($this->aluno);

            $em = $this->getDoctrine()->getManager();
            $em->persist($this->entity);
            $em->flush();

            //return $this->redirectToRoute("{$this->entityName}_index");
            return $this->redirectToRoute('perfil_aluno_profile', [
                'id' => $this->aluno->getId(),
            ]);
        }

        return $this->render($this->getTemplateManager()->getNew(), [
            'form' => $form->createView(),
            'entityName' => $this->entityName,
            'template' => (array) $this->getTemplateManager(),
        ]);
    }

    /**
     * @Route("/{id}", name="acompanhamento_show", methods="GET")
     * @ParamConverter("entity", class="App\Entity\Acompanhamento")
     * @IsGranted("acompanhamento_show", subject="entity")
     */
    public function show(EntityInterface $entity): Response
    {
        return parent::show($entity);
    }

    /**
     * @Route("/{id}/edit", name="acompanhamento_edit", methods="GET|POST")
     * @ParamConverter("entity", class="App\Entity\Acompanhamento")
     * @IsGranted("acompanhamento_edit", subject="entity")
     */
    public function edit(Request $request, EntityInterface $entity): Response
    {
        return parent::edit($request, $entity);
    }

    /**
     * @Route("/{id}", name="acompanhamento_delete", methods="DELETE")
     * @ParamConverter("entity", class="App\Entity\Acompanhamento")
     * @IsGranted("acompanhamento_delete", subject="entity")
     */
    public function delete(Request $request, EntityInterface $entity): Response
    {
        return parent::delete($request, $entity);
    }

    protected function getTemplateManager(): TemplateManager
    {
        $templateManager = parent::getTemplateManager();
        $templateManager->setNew('acompanhamento/new.html.twig');
        $templateManager->setEdit('acompanhamento/edit.html.twig');

        return $templateManager;
    }

    /**
     * @Route("/{id}/pdf", name="acompanhamento_report_pdf", methods="GET")
     * @ParamConverter("entity", class="App\Entity\Acompanhamento")
     * @IsGranted("acompanhamento_show", subject="entity")
     */
    public function reportPdf(EntityInterface $entity, PdfGenerator $pdfGenerator): Response
    {
        $html = $this->renderView('acompanhamento/report_pdf.html.twig', [
            'register' => $entity,
            'title' => 'Formulário Acompanhamento',
        ]);

        $pdfGenerator->setStyle('report_pdf.css');
        $pdfGenerator->setContent($html);

        return $pdfGenerator->generate();
    }
}

templates/acompanhamento/edit.html.twig
{% extends 'generic/edit.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('assets/js/ckeditor/ckeditor.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/js/ckeditor/adapters/jquery.js') }}" type="text/javascript"></script>
    <script type="text/javascript">
        $(function() {
            $('textarea.ckeditor').ckeditor();
        });
    </script>
{% endblock %}

templates/acompanhamento/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Listagem {{ entityName|capitalize }}{% endblock %}

{% set registerListAttr = [] %}
{% for register in registers %}
    {% set registerListAttr = registerListAttr|merge ([{
        'Id': register.id,
        'Data Hora': register.dataHora ? register.dataHora|date('d/m/Y H:i:s') : '',
        'Aluno' : register.aluno.nome,
        'Descrição': register.descricao,
    }]) %}
{% endfor %}

{% set actionList = {
    'new': false,
    'show': true,
    'edit': false,
    'delete': false,
    'pdf': true,
} %}

{% block body %}
    {% include 'generic/_body_title.html.twig' with {title: 'Listagem - '~entityName|capitalize} %}
    {{ include(template.indexActions) }}
    {{ include(template.indexFooter) }}
{% endblock %}

templates/acompanhamento/new.html.twig
{% extends 'generic/new.html.twig' %}

{% block body %}
    {{ parent() }}
    {% block timeline %}
        {{ render(controller(
            'App\\Controller\\TimelineController::index', {'entityOpenner':'acompanhamento', 'orientation':'horizontal'}
        )) }}
    {% endblock %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('assets/js/ckeditor/ckeditor.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/js/ckeditor/adapters/jquery.js') }}" type="text/javascript"></script>
    <script type="text/javascript">
        $(function() {
            $('textarea.ckeditor').ckeditor();
        });
    </script>
{% endblock %}

templates/acompanhamento/report_pdf.html.twig
<head>
    <title>{{ title | upper}}</title>
</head>
<body>
<div>
    <h1 class="acompanhamento_titulo">{{ title | upper}} </h1>

    <table class="acompanhamento_table">
        <tbody>
            <tr>
                <th>Aluno:</th>
                <td>{{ register.aluno }}</td>
                <th>Data Nascimento:</th>
                <td>{{ register.aluno.dataNascimento ? register.aluno.dataNascimento|date('d/m/Y') : '' }}</td>
            </tr>
            <tr>
                <th>Educador:</th>
                <td>{{ register.usuario }}</td>
                <th>Data/Hora:</th>
                <td>{{ register.dataHora ? register.dataHora|date('d/m/Y H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Escola:</th>
                <td>{{ register.usuario.escola.nome }}</td>
                <th>Endereço:</th>
                <td>{{ register.usuario.escola.endereco }}</td>
            </tr>
        </tbody>
    </table>

    <div class="acompanhamento_div_acompanhamento">
        <span><strong>Acompanhamento:</strong></span>
        <div class="acompanhamento_descricao">
            {{ register.descricao | raw}}
        </div>
    </div>
</div>
</body>

templates/acompanhamento/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Acompanhamento{% endblock %}

{% block body %}
    {% include 'generic/_body_title.html.twig' with {title: entityName|capitalize} %}

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ register.id }}</td>
            </tr>
            <tr>
                <th>Data Hora</th>
                <td>{{ register.dataHora ? register.dataHora|date('d/m/Y H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Descrição</th>
                <td>{{ register.descricao | raw}}</td>
            </tr>
        </tbody>
    </table>

    {{ include(template.showActions) }}

{% endblock %}